#!/bin/sh
# shellcheck disable=SC2155,SC2015,SC2046
grep(){
  LANG=C
  rcase() {
    while read -r p || [ -n "$p" ] ; do
      case "$p" in
        *${1}*)
          [ "$2" != "-q" ] && { IFS=""; printf "%s\\n" "$p"; } || { exit 0; }
        ;;
      esac    
    done <&0
    exit 1
  }
  rcase "${1:?grep requires an argument}" "${2:+-q}" || exit 1
}
ulist=$(
  IFS=""; while read -r p || [ -n "$p" ]; do
    p="${p##*bin}"; p="${p#*>}"; p="${p%%<*}"
    unset IFS; printf "%s " "$p"
  done << EOF
$(IFS=""; curl -sL "https://git.unix.lgbt/Mia/shapplet/src/branch/head/bin" | grep "href=*head/bin/")
EOF
) # list of currently existing utils at shapplets
for i in $ulist; do
  IFS=""; export c="$(curl -sL \"https://git.unix.lgbt/Mia/shapplet/raw/branch/head/bin/$i\")"
  eval $(while read -r p || [ -n "$p" ]; do
    printf "%s\\n" "$p"
    # oddly this while read loop is REQUIRED
  done << EOF
${i}(){
  eval ${c}
}
EOF
)
done
